language: ruby
rvm:
- 2.3.3

sudo: false

script:
- bundle exec jekyll build
- ls -ltr
- ls -ltr _site

deploy:
# Deploy master pandegroup branch to http://openmm.org
- provider: s3
  skip_cleanup: true
  detect_encoding: true
  access_key_id:
    secure: "NxSyvMW8cjFtyVAW+7oG8SnNefycdEIynbkiceBWWWSqXsukjBc0u0Xb/w1T5y035SWRpigTLtpNCK6VLWu6K7ZMc3WqfNStVjFarlbqB6QSoq8zTSCXwWN22zj/34vVCb9yOTXh2H8a35bF6Q7wWIdR0BM35B4mtQRrCEIUkYQ="
  secret_access_key:
    secure: "Qe5jLB3vsi+iyLGAQOYWkE/klLpggbRDHt72ohEmzJur6U/Li0eA4XwMEFyHApJg6bUanJFiEbs22XzBtI/qG9ys/69n4xfQxJq+wZjfvmO0WUSYQYdqJ+opo26wju/KUbmWlF48SKORW3oDnK7Oppbe2DmiVOINl/X02HRu72c="
  bucket: openmm.org
  local_dir: _site
  region: us-west-1
  endpoint: openmm.org.s3-website-us-west-1.amazonaws.com
  on:
    repo: openmm/openmm-org
    branch: master
# Deploy preview pandegroup branch to http://openmm.org/preview
- provider: s3
  skip_cleanup: true
  detect_encoding: true
  access_key_id:
    secure: "NxSyvMW8cjFtyVAW+7oG8SnNefycdEIynbkiceBWWWSqXsukjBc0u0Xb/w1T5y035SWRpigTLtpNCK6VLWu6K7ZMc3WqfNStVjFarlbqB6QSoq8zTSCXwWN22zj/34vVCb9yOTXh2H8a35bF6Q7wWIdR0BM35B4mtQRrCEIUkYQ="
  secret_access_key:
    secure: "Qe5jLB3vsi+iyLGAQOYWkE/klLpggbRDHt72ohEmzJur6U/Li0eA4XwMEFyHApJg6bUanJFiEbs22XzBtI/qG9ys/69n4xfQxJq+wZjfvmO0WUSYQYdqJ+opo26wju/KUbmWlF48SKORW3oDnK7Oppbe2DmiVOINl/X02HRu72c="
  bucket: openmm.org
  local-dir: _site
  upload-dir: preview
  region: us-west-1
  endpoint: openmm.org.s3-website-us-west-1.amazonaws.com
  acl: public_read
  on:
    repo: openmm/openmm-org
    branch: preview
# Test preview deploy
- provider: s3
  skip_cleanup: true
  detect_encoding: true
  access_key_id:
    secure: "NxSyvMW8cjFtyVAW+7oG8SnNefycdEIynbkiceBWWWSqXsukjBc0u0Xb/w1T5y035SWRpigTLtpNCK6VLWu6K7ZMc3WqfNStVjFarlbqB6QSoq8zTSCXwWN22zj/34vVCb9yOTXh2H8a35bF6Q7wWIdR0BM35B4mtQRrCEIUkYQ="
  secret_access_key:
    secure: "Qe5jLB3vsi+iyLGAQOYWkE/klLpggbRDHt72ohEmzJur6U/Li0eA4XwMEFyHApJg6bUanJFiEbs22XzBtI/qG9ys/69n4xfQxJq+wZjfvmO0WUSYQYdqJ+opo26wju/KUbmWlF48SKORW3oDnK7Oppbe2DmiVOINl/X02HRu72c="
  bucket: openmm.org
  local-dir: _site
  upload-dir: preview
  region: us-west-1
  endpoint: openmm.org.s3-website-us-west-1.amazonaws.com
  acl: public_read
  on:
    repo: openmm/openmm-org
    branch: fix-s3-push

notifications:
  email: false
