language: python
deploy:
  provider: s3
  secret_access_key:
    secure: AsgDF0YzW6OqwsuqNJB7GAC595KY1/iDzu5nV839zUBTI99mmXY/oUMv2IeltHGpozCH3Szl5IcgZWgwd5ttrj8lfCSDpMbIepSsHm3J6qsh4qFZJ6g7VCjAe9AN0VWeDB1mDrWEHUcaFREIBmswn1Ixcpon1txYJCKzxYvtERs=
  access_key_id:
    secure: IBCQMRao7VJaFsnIb1Sjo90KsAdKvNMg913N5i7TJGdc9LKP3PiX7p2BSR1ZsuTHHZWWz7DYzo09/IpTInXRU1QAb8SlRLeneOUKHsH33Y2Gkq22EtXf+JbsAoVW7qoty039J67HZMOH/bSucTKNwgGRYW6YMdeiGrpTbyNMHes=
  bucket: "openmm-staging"
  skip_cleanup: true
  local_dir: landing-page
  detect_encoding: true
