language: python

env:
  global:
  - secure: ZWb2y+DlPlVCRhfc1sUgtAQiqCpJAdUmOK1uetehxmBUFJeFztbP08ZgQx19kSsdNhrDxAgIo+jExy6B/vj6EYU7/xPTxS/8pm0TXplTOsvSbu9QZutwoE9X3bN2JI0cuWhPMVaJTkFmSG21Lt4ktwGBEYhS/EV58EKRUUMhfJI=
  - secure: h9aekxGsnnmw4KJYSBDCtjId6Jm+zqjSaPX1Jx7267VE5RWQKDIuMmMXYLz3cnr5LhYaIeAMntWphRTg7Pg7qx43/PcT+qDuM2Q0TOE4kXc2krHWxqu94UZWXxmLB+Pv+eHBEpnb2qu4HD3X9BiDlcdHQdl5XjPpc1JJ1mS9NGM=


install:
- pip install boto

script:
- python push_to_s3.py
- echo "Complete"
