language: python
env:
  global:
  - secure: IEaBoYLhLIyU/oLnWA3XL7Mk01pO8B3txe28JhdgrUgdQnfqAzwQ5oiLkFGGTprO2Z9h7ek1x6z+dPOZu0A++8pvctiUUD29H1gZ1gjpH4PpECpMNaGmRygUKboH/xBwb5S7/xUZn6yQCgA5U3WEqVUOtNOlNwvsASGXbhsZs20=
  - secure: hFAEnk3GvXkdOPrW7RTi770TzXQGqE1vpZnz7jmizBQvUBpXPxPR8mUixSyyP3r1STRUbixZBKRtL8oQ7Wg7QzkWkSKUp79bjKVsiPN6ZIyCo/uR85jHncMjeA30nLVF05SEvoWWPCVqvFg+YhtFvfezyeVH0VKlfR/c/v6jQ6s=
install:
- pip install boto
script:
- python push_to_s3.py
- echo "Complete"
