language: ruby
sudo: false

env:
  global:
  - secure: THXt8oCzrJBEV1W7SwBkjMVnHLe+cAtzOg9A4LyfWSva7OeqyY/bMrnXhf1r9Ssp324xuoupxsDqIop6nc5525cOKQv07dD6qGIAPjC6pbjInGJQjpbWMd86xb15MfxyAxS1mqEO1vr2tAjoITxSMrpaEXrlPpzzxKVmQspzQcU=
  - secure: DomMIZE0q1PLJpNI6Tj39MaAWvQM5ak4oLD8vXgIPd5c8e0ano/jlvtqHLbyfsLE7ZddMEiIFGfm7hSbW9JkNDLoVVWA+fRPWem1OxgATEKF/n6jkl457wMfQjHcMtEngCtuPIqe6waVxJXm/GSSxefpmwhwBC4E1z3OvbGjVp0=

script:
  - echo "No build required. Just deployment"

deploy:
  provider: s3
  skip_cleanup: true
  local_dir: landing-page
  detect_encoding: true
  access_key_id:  "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: openmm.org
  endpoint: openmm.org.s3-website-us-west-1.amazonaws.com
  # Debugging: modify the bucket / endpoint to point to a staging bucket
  # so that you can view the result there
  # bucket: openmm-staging
  # endpoint: openmm-staging.s3-website-us-east-1.amazonaws.com
  on:
    branch: master
