language: ruby
rvm:
  - 2.3.3
sudo: false

# Travis will automatically run 'bundle install'

script:
  - bundle exec jekyll build

deploy:
  provider: s3
  skip_cleanup: true
  local_dir: _site
  detect_encoding: true
  access_key_id:
    secure: "rmEc9f9zcPEdb75SBL9dIIiP48LlI9gOjpFvvy20C/paBqpuJxWn2k27y4hnZMHgDa+4x2xGTPkzL4Jp/+URYWbrbPgLM9cuttruUY+8s0wP3GLEvvhfrtXMWn7pCdRQiQpx2MqOCdnf8rc67Gg8esBptnfQBBt3uU4BBps34VI="
  secret_access_key:
    secure: "SkmL4Bn0Rq1skExKaF6HPBSPBaM7zf6ZCQgt/XsJAi2ZkSSOdfpND/K9xDDc9TzGVlu2qK2EcLsWupavQJiL1OEwsy8rC42OCFOLXyt3Qc3kZ+TFot6wx1d+X9IPw4BqjW5UME7TksU/bCxHoVjbuEBjOCQQzdNNQuVkFKaxVk4="
  bucket: openmm-org-preview
  endpoint: http://openmm-org-preview.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  on:
    branch: preview
