language: ruby
rvm:
- 2.3.7

sudo: false

script:
- bundle exec jekyll build
- ls -ltr
- ls -ltr _site

deploy:
  provider: s3
  access_key_id:
    secure: vnw8OYMSzgi51p9ABoQTnQjFMG974zX2KIDR0TVCj8YeR1LRiINWV1hEHZhDTEEzSFX4yIB7nilgku0Ajf2F1opTmDtCkelxXY88wsdKG82k6mw/dgoLbWi1ZuDMj8KbOWmcs76DZpjnMt4s487OHLccXxb5eeCCRKVTfCGdarc=
  secret_access_key:
    secure: lmMJVZFQONll1zksUaSh7otKEfji+fz0c1ACa/vhj42sgkJYHtrKYgoRajd8KxoT7xkfp6Ao1kuvRdw5olK0qeQGAtwtcPAPd3I1WdNJtMSaMMVdU/EGKt7ZW0dHFvzHGO29ZYJC4SUSNRvEQsNZLik1T6aqAOdDvWSE69rVCSg=
  skip_cleanup: true
  bucket: openmm-org-preview
  local-dir: _site
  acl: public_read
  on:
    repo: jchodera/openmm-org
    branch: preview

notifications:
  email: false
